version: 2.1
orbs:
  snyk: snyk/snyk@0.0.8
jobs:
  build:
    docker:
      - image: circleci/node:12.10.3-browsers

    working_directory: ~/repo

    environment:
      SNYK_TOKEN: 506a9960-5b66-476e-8f90-0e8571dafd4a

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn lint
      - run: yarn test

      - snyk/scan:
          fail-on-issues: false
          monitor-on-build: false
          severity-threshold: high